---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo-dash
  labels:
    app: rollouts-demo-dash
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rollouts-demo-dash
  template:
    metadata:
      labels:
        app: rollouts-demo-dash
    spec:
      containers:
        - name: rollouts-demo-dash
          image: "aniruth004/nodejs_envision:latest"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
  strategy:
     canary: 
       steps:
       - setWeight: 20
       - pause: {}
